/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.guava)
    implementation("org.xerial:sqlite-jdbc:3.45.1.0")
}

testing {
    suites {
        val test = named<JvmTestSuite>("test") {
            // Replaces useJUnit("4.13.2")
            useJUnitJupiter() 
        }
    }
}

javafx {
    // Specify the JavaFX version
    version = "21" 
    
    // Declare the JavaFX modules you need
    modules("javafx.controls", "javafx.fxml")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<JavaExec>("run") {
    jvmArgs(
        "--enable-native-access=javafx.graphics",
        "--add-opens=javafx.graphics/com.sun.glass.utils=ALL-UNNAMED"
    )
}